name: RestAssured Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'src/test/resources/TestSuites/regressionTest.xml'
        type: choice
        options:
          - src/test/resources/TestSuites/regressionTest.xml
          - src/test/resources/TestSuites/smokeTest.xml
          - src/test/resources/TestSuites/authTest.xml

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean and compile tests
        run: mvn clean compile

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_suite }}" != "" ]; then
            mvn clean install -Dfile="${{ github.event.inputs.test_suite }}"
          else
            mvn clean install -Dfile="src/test/resources/TestSuites/regressionTest.xml"
          fi
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            test-output/
          retention-days: 30

      - name: Upload extent reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: |
            ExtentReports/
            reports/
          retention-days: 30