name: RestAssured Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: true
        default: 'src/test/resources/TestSuites/regressionTest.xml'
        type: choice
        options:
          - src/test/resources/TestSuites/regressionTest.xml
          - src/test/resources/TestSuites/smokeTest.xml
          - src/test/resources/TestSuites/authTest.xml

jobs:
  test:
    runs-on: ubuntu-latest

    services:
    # Optional: Add database service if your API needs it
    # postgres:
    #   image: postgres:13
    #   env:
    #     POSTGRES_PASSWORD: postgres
    #   options: >-
    #     --health-cmd pg_isready
    #     --health-interval 10s
    #     --health-timeout 5s
    #     --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup .NET for the API
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Setup Java for RestAssured tests
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build the .NET API
      - name: Restore .NET dependencies
        run: dotnet restore
        working-directory: ./api

      - name: Build .NET API
        run: dotnet build --no-restore
        working-directory: ./api

      # Start the API in background
      - name: Start .NET API
        run: |
          dotnet run --project ./api &
          API_PID=$!
          echo "API_PID=$API_PID" >> $GITHUB_ENV
          echo "Started API with PID: $API_PID"
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_URLS: http://localhost:5000

      # Wait for API to be ready
      - name: Wait for API to start
        run: |
          echo "Waiting for API to start..."
          timeout 60 bash -c 'until curl -f http://localhost:5000/health || curl -f http://localhost:5000; do sleep 2; done'
          echo "API is ready!"

      # Compile Java tests
      - name: Clean and compile tests
        run: mvn clean compile

      # Run the tests against the running API
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_suite }}" != "" ]; then
            mvn clean install -Dfile="${{ github.event.inputs.test_suite }}"
          else
            mvn clean install -Dfile="src/test/resources/TestSuites/regressionTest.xml"
          fi
        env:
          BASE_URL: http://localhost:5000
        continue-on-error: true

      # Stop the API
      - name: Stop .NET API
        if: always()
        run: |
          if [ ! -z "$API_PID" ]; then
            echo "Stopping API with PID: $API_PID"
            kill $API_PID || true
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            test-output/
          retention-days: 30

      - name: Upload extent reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: |
            ExtentReports/
            reports/
          retention-days: 30

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/testng-results.xml
          reporter: java-junit
          fail-on-error: false