name: RestAssured Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean and compile
        run: mvn clean compile

      - name: Run regression tests
        run: mvn test -Dsurefire.suiteXmlFiles=regressionTest.xml
        continue-on-error: true # Continue even if tests fail to generate reports

      - name: Generate test report
        if: always() # Run even if tests fail
        run: |
          echo "Test execution completed"
          ls -la target/surefire-reports/ || echo "No surefire reports found"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            test-output/
          retention-days: 30

      - name: Upload extent reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: |
            ExtentReports/
            reports/
          retention-days: 30

      - name: Publish test results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: TestNG Results
          path: target/surefire-reports/testng-results.xml
          reporter: java-junit
          fail-on-error: false